# Generated by Django 6.0.4 on 2026-05-02 05:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='partner',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partners', to='api.user'),
        ),
    ]
