# Generated by Django 6.0.4 on 2026-05-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_car_features_alter_partner_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'platform_settings',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
