# Generated by Django 6.0.4 on 2026-05-03 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_platformsetting_booking_booking_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='kyc_reviewed_by',
            field=models.ForeignKey(blank=True, db_column='kyc_reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to='api.user'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
