# Generated by Django 6.0.4 on 2026-05-05 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_car_location_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_fee_reference',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_fee_refund_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_fee_refunded_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_fee_verified',
        ),
        migrations.AddField(
            model_name='booking',
            name='partner_gcash_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PartnerSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_owed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled')], default='pending', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='api.partner')),
            ],
            options={
                'db_table': 'partner_settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
