# Generated by Django 6.0.4 on 2026-05-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_booking_booking_fee_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
