# Generated by Django 6.0.4 on 2026-05-07 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_rental_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.booking'),
        ),
    ]
