# Generated by Django 6.0.4 on 2026-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='business_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='business_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
