# Generated by Django 6.0.4 on 2026-05-15 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_partner_business_lat_partner_business_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='agreement_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='agreement_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='PartnerBoostRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('boost_type', models.CharField(choices=[('featured', 'Featured Listing'), ('spotlight', 'Spotlight Banner')], default='featured', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('paid', 'Paid & Active'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('duration_months', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months')], default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('partner_message', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_requests', to='api.partner')),
            ],
            options={
                'db_table': 'partner_boost_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
