# Generated by Django 6.0.4 on 2026-05-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customerprofile_agreement_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='inquiry_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_messages', to='api.partner'),
        ),
    ]
